### PR TITLE
ensure that file permissions are kept for distinfo and data directories

### PR DESCRIPTION
**Pull request by mboisson**
This addresses https://github.com/MrMino/wheelfile/issues/17

### CODE REVIEW

**Comment by MrMino** [comment]
I would like to add some tests to this (most of `wheelifle` was done using test-first). It would be very helpful if you added it, so that when I actually get back to developing this it would be as easier for me to pull. You can put them into separate `test_*` file, I'll handle the rest.

**Comment by mboisson** [comment]
Ok, I realized there were already tests for ZipInfo for `dist` and `data` directories, but they were marked as `xfail` because `writestr_distinfo` and `writestr_data` did not propagate zinfo information. Therefore, instead of writing new tests, I fixed `writestr_distinfo` and `writestr_data` and generalized the code I wrote using a new internal function `_clone_and_rename_zipinfo`, which clones the `ZipInfo` object under a new filename, and used that function in all 3 instances (`from_wheelfile`, `writestr_data` and `writestr_distinfo`)

**Comment by mboisson** [comment]
Note that I am unsure about how to run the tests, so there may be some issues.

**Comment by MrMino** [comment]
@mboisson thank you! This will be the first thing I release as soon as I get back to OSS, along with the other metadata stuff. Sorry for the long wait.

**Comment by MrMino** [comment]
Superseeded by 7b69c5aa14152abb2785b5a9e9fe56244c000168.

**Pull request closed without merging**
